# Generated by Django 5.1.2 on 2024-10-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HealthCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='healthdata',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Sedentary'), ('lightly_active', 'Lightly Active'), ('moderately_active', 'Moderately Active'), ('very_active', 'Very Active')], default='Sedentary', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthdata',
            name='diet_preference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='fitness_goal',
        ),
        migrations.AddField(
            model_name='healthdata',
            name='conditions',
            field=models.ManyToManyField(to='users.healthcondition'),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='fitness_goal',
            field=models.ManyToManyField(to='users.fitnessgoal'),
        ),
    ]
