# Generated by Django 5.1.2 on 2024-10-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_fitnessgoal_healthcondition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdata',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Sedentary'), ('lightly_active', 'Lightly Active'), ('moderately_active', 'Moderately Active'), ('very_active', 'Very Active')], default='Sedentary', max_length=50),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='diet_preference',
            field=models.CharField(choices=[('vegetarian', 'Vegetarian'), ('non_vegetarian', 'Non-Vegetarian'), ('vegan', 'Vegan'), ('jain', 'Jain')], default='Vegetarian', max_length=50),
        ),
    ]
