# Generated by Django 5.1.2 on 2024-10-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_healthdata_activity_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthdata',
            old_name='activity_level',
            new_name='selectedActivity',
        ),
        migrations.RenameField(
            model_name='healthdata',
            old_name='conditions',
            new_name='selectedConditions',
        ),
        migrations.RenameField(
            model_name='healthdata',
            old_name='diet_preference',
            new_name='selectedDiet',
        ),
        migrations.RenameField(
            model_name='healthdata',
            old_name='fitness_goal',
            new_name='selectedGoals',
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='height',
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='weight',
        ),
        migrations.AddField(
            model_name='healthdata',
            name='currentWeightKg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current Weight in kg', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='heightCm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='targetWeight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Target Weight in kg', max_digits=5, null=True),
        ),
    ]
