# Generated by Django 5.1.2 on 2024-10-31 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthdata',
            old_name='date_of_birth',
            new_name='birthdate',
        ),
    ]
