# Generated by Django 5.1.2 on 2024-11-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, default="This is your bio section! You can edit it to share a little about yourself, your interests, or anything you'd like others to know.", null=True),
        ),
    ]
